# Generated by Django 5.1.6 on 2025-03-01 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profile_piture',
            new_name='profile_picture',
        ),
    ]
